import requests
import streamlit as st


def get_result(input_text:str) -> str:
    
    """
    This function returns the result generated by LLM 
    
    Parameters
    ----------
    input_text: str
                User's question
    
    Returns
    -------
    str
        Returns string generated by LLM through API call.

    """
    
    
    # Posting the user question to LLM and RAG Chain via API
    response = requests.post(
        "http://localhost:8000/analysis/invoke",
        json={'input': input_text}
    ) 
    
    print(f"Response success: {response}")
    
    # Output from LLM model
    return response.json()['output']


# Web page title
st.title("Survey Data Analysis")
# User's question
input_text = st.text_input("Ask question here!!")

# Displaying result
if input_text:
    st.write(get_result(input_text=input_text))